"""Local keyword wake-word detection via sherpa-onnx KWS.

The QWEN realtime backend's cloud ASR (fixed ``qwen3-asr-flash-realtime``)
transcribes short Chinese wake phrases unreliably ("你好小白" came back as
"要不"/"要来"/"Yeah"), so wake detection needs a local engine. sherpa-onnx
keyword spotting runs a ~3.3 MB Chinese Zipformer transducer on the Pi 5 CPU
at realtime speed and only fires for the configured keyword.

Model layout (downloaded once, see the deploy notes):
    <model_dir>/tokens.txt
    <model_dir>/encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx
    <model_dir>/decoder-epoch-12-avg-2-chunk-16-left-64.onnx
    <model_dir>/joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx
    <model_dir>/keywords.txt      (generated by sherpa-onnx-cli text2token)

``KeywordWakeDetector`` wraps a single ``KeywordSpotter`` stream. Callers
feed 16 kHz int16 chunks every ~60 ms; :meth:`feed` drains the decoder and
returns the matched keyword (the ``@``-name from keywords.txt) or ``None``.
"""

from __future__ import annotations

import logging
import os
import threading
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

KWS_MODEL_DIR = Path(
    os.environ.get(
        "YROBOT_KWS_MODEL_DIR",
        "/home/pollen/stt-models/sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01",
    )
).expanduser()


class KeywordWakeDetector:
    """Streaming sherpa-onnx keyword spotter for a single wake phrase."""

    def __init__(self, model_dir: Path = KWS_MODEL_DIR, num_threads: int = 2) -> None:
        # Import lazily so the rest of YRobot (and its tests) do not
        # require sherpa-onnx to be installed — only the wake path does.
        from sherpa_onnx import keyword_spotter as ks

        model_dir = Path(model_dir)

        def _pick(pattern: str) -> Path:
            # Model archives ship with epoch-specific names (12 for the
            # wenetspeech-3.3M, 13 for the zh-en-3M-2025); probe instead of
            # hard-coding. chunk-16 variants are preferred for KWS.
            cands = sorted(model_dir.glob(pattern))
            if not cands:
                raise FileNotFoundError(f"{model_dir}/{pattern}")
            return cands[0]

        self._kws = ks.KeywordSpotter(
            tokens=str(model_dir / "tokens.txt"),
            encoder=str(_pick("encoder-*chunk-16-left-64.int8.onnx")),
            decoder=str(_pick("decoder-*chunk-16-left-64.onnx")),
            joiner=str(_pick("joiner-*chunk-16-left-64.int8.onnx")),
            keywords_file=str(model_dir / "keywords.txt"),
            num_threads=num_threads,
            provider="cpu",
            keywords_score=float(os.environ.get("YROBOT_KWS_KEYWORDS_SCORE", "1.0")),
            keywords_threshold=float(os.environ.get("YROBOT_KWS_THRESHOLD", "0.25")),
        )
        self._stream = self._kws.create_stream()
        self._lock = threading.Lock()
        logger.info(
            "sherpa-onnx keyword spotter loaded: %s (keywords_score=%s, keywords_threshold=%s)",
            model_dir,
            os.environ.get("YROBOT_KWS_KEYWORDS_SCORE", "1.0"),
            os.environ.get("YROBOT_KWS_THRESHOLD", "0.25"),
        )

    def feed(self, samples_int16: np.ndarray) -> str | None:
        """Feed a 16 kHz int16 chunk; return the matched keyword or ``None``.

        ``samples_int16`` should be a 1-D array of 16 kHz int16 samples
        (e.g. one 60 ms mic chunk = 960 samples). The decoder is drained
        on every feed so a keyword that spans several chunks is still
        caught; a match resets the stream so the same phrase can fire
        again later.
        """
        with self._lock:
            audio = samples_int16.astype(np.float32) / 32768.0
            self._stream.accept_waveform(16000, audio)
            result: str | None = None
            while self._kws.is_ready(self._stream):
                self._kws.decode_stream(self._stream)
                hit = self._kws.get_result(self._stream)
                if hit:
                    result = hit
                    self._kws.reset_stream(self._stream)
            return result

    def reset(self) -> None:
        with self._lock:
            self._kws.reset_stream(self._stream)
